class AppUrls {
  AppUrls._();

  static const String baseUrl = 'https://rosybrown-ant-846135.hostingersite.com';
  static const Duration timeout = Duration(seconds: 20);

  static const String signUp = '/api/auth/signup';
  static const String signIn = '/api/auth/login';
  static const String createBusiness = '/api/businesses';
  static const String getAllBusinesses = '/api/businesses';
  static const String updateBusiness = '/api/businesses';
  static const String profile = '/api/profile';
  static const String deleteAccount = '/api/profile/delete-account';
  static const String logout = '/api/auth/logout';
  static const String createVendor = '/api/vendors';
  static const String updateVendor = '/api/vendors';
  static const String createCustomer = '/api/customers';
  static const String updateCustomer = '/api/customers';
  static const String expenseCategories = '/api/dropdowns/categories';
  static const String paymentMethods = '/api/dropdowns/payment-methods';
  static const String createExpense = '/api/expenses';
  static const String expensePdf = '/api/expenses';
  static const String updateExpense = '/api/expenses';
  static const String deleteExpense = '/api/expenses';
  static const String createCategory = '/api/categories';
  static const String updateCategory = '/api/categories';
  static const String deleteCategory = '/api/categories';
  static const String createInvoice = '/api/invoices';
  static const String updateInvoice = '/api/invoices';
  static const String deleteInvoice = '/api/invoices';
  static const String createEmployee = '/api/employees';
  static const String getAllEmployees = '/api/employees';
  static const String updateEmployee = '/api/employees';
  static const String deleteEmployee = '/api/employees';
  static const String createTask = '/api/tasks';
  static const String getAllTasks = '/api/tasks';
  static const String updateTask = '/api/tasks';
  static const String deleteTask = '/api/tasks';
  static const String deleteTaskAttachment = '/api/tasks';
  static const String createAsset = '/api/assets';
  static const String getAllAssets = '/api/assets';
  static const String updateAsset = '/api/assets';
  static const String deleteAsset = '/api/assets';
  static const String balanceSheet = '/api/reports/balance-sheet';
  static const String trialBalance = '/api/reports/trial-balance';
  static const String chartOfAccounts = '/api/chart-of-accounts';
  static const String chartOfAccountsDropdown = '/api/dropdowns/chart-of-accounts';
  static const String accountingPeriods = '/api/accounting-periods';
  static const String accountingPeriodsCurrent = '/api/accounting-periods/current';
  static const String vouchers = '/api/vouchers';
  static const String vouchersPendingApprovals = '/api/vouchers/pending-approvals';
  static const String dashboard = '/api/dashboard';
  static const String ledger = '/api/ledger';
  static const String incomeStatement = '/api/reports/income-statement';
  static const String teamMembers = '/api/team-members';
}
